#!/bin/bash
#SBATCH --qos=blanca-giglio
#SBATCH --account=blanca-giglio
#SBATCH --partition=blanca-giglio
#SBATCH --export=NONE
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --job-name=ohc_derive
#SBATCH --output=%x.%j.out
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=katie.mills@colorado.edu
#SBATCH --mem=256GB
#SBATCH --exclude=blanca-g6-u21

module purge
module load anaconda/2023.09
conda activate ohc_crosscheck

cd $SLURM_SUBMIT_DIR
tag=260908-OP20260507
results=/scratch/alpine/wimi7695/ohc_prod/results_260908
python run.py \
    ${results}/OHC_${tag}_*.nc \
    --level 700_2000 \
    --time-window 2005:2025 \
    --quantities ohca,ohu,ohca_trend,ohu_trend \
    --mask contiguous_from_top \
    --bathy /scratch/alpine/wimi7695/ohc_prod/params/etopo60.cdf \
    --tag  ${tag} \
    --provenance-link https://github.com/ocean-grid-processing/provenance/blob/main/README.md \
    --code-version https://github.com/ocean-grid-processing/ohc_derive/releases/tag/1.0.0 \
    --out ${results}
